### ISSUE TITLE
同款电脑，为什么我直接用efi声卡和hdmi有问题呢

### ISSUE THREAD

**Issue by 1xiaocainiao** [wing-ho/HP-AS110TU-Hackintosh#1]
applealc加了，hdmi外接显示器颜色不对

**Comment by wing-ho** [comment]
@1xiaocainiao 我是使用AppleHDA Patcher给AppleHDA.kext打补丁的方式来实现的，需要把打过补丁的AppleHDA.kext替换掉位于/system/library/extensions的AppleHDA.kex，第二种方式就是直接添加applealc.kext，删除CLOVER/kexts/Other/HDAEnabler.kext，然后在clover中注入layout-id
`
<key>Devices</key>
<dict>
    <key>Audio</key>
    <dict>
        <key>Inject</key>
        <integer>3</integer>
    </dict>
</dict>
`
另外外接显示器颜色不对的问题，我想可以注入EDID的方式可以解决。
参考文章：
[Clover 注入EDID解决笔记本内屏黑屏的问题](https://imac.hk/clover-injection-edid.html)
[EDID Manager工具下载链接](https://extron-electronics-edid-manager.software.informer.com/1.0/)

**Comment by 1xiaocainiao** [comment]
> @1xiaocainiao 我是使用AppleHDA Patcher给AppleHDA.kext打补丁的方式来实现的，需要把打过补丁的AppleHDA.kext替换掉位于/system/library/extensions的AppleHDA.kex，第二种方式就是直接添加applealc.kext，删除CLOVER/kexts/Other/HDAEnabler.kext，然后在clover中注入layout-id
> `<key>Devices</key> <dict> <key>Audio</key> <dict> <key>Inject</key> <integer>3</integer> </dict> </dict>`
> 另外外接显示器颜色不对的问题，我想可以注入EDID的方式可以解决。
> 参考文章：
> [Clover 注入EDID解决笔记本内屏黑屏的问题](https://imac.hk/clover-injection-edid.html)
> [EDID Manager工具下载链接](https://extron-electronics-edid-manager.software.informer.com/1.0/)

感谢分享
