### ISSUE TITLE
请问您的hdpi 1080P是60hz还是40hz?

### ISSUE THREAD

**Issue by xhssme** [wing-ho/HP-AS110TU-Hackintosh#2]
您好，我也是同款AS110TU，用了您的EFI，可是屏幕所有的分辨率都只有40hz，您的也是这样吗？
![Jietu20190913-143830](https://user-images.githubusercontent.com/42639427/64842243-2b067e00-d634-11e9-953e-a2ad7b5b6c91.jpg)

**Comment by su-shi** [comment]
我也碰到了，通过开启hdmi2.0补丁，可以看到60Hz

**Comment by 1xiaocainiao** [comment]
> 我也碰到了，通过开启hdmi2.0补丁，可以看到60Hz

请问是加的什么，我加了whatevergreeen 那个 -cdfon enable-hdmi20属性 在启动参数没起作用呢
