### ISSUE TITLE
期待大神的Big Sur

### ISSUE THREAD

**Issue by ulpyuxa** [wing-ho/HP-AS110TU-Hackintosh#5]
期待大神的Big Sur

**Comment by wing-ho** [comment]
@ulpyuxa
可能要让你失望了，到目前为止没有计划继续折腾Big Sur。WSL2出来之后，我把笔记本的系统换回windows了，厌烦了黑苹果每次升级系统后都需要调整配置。

**Comment by ulpyuxa** [comment]
好的，大神永远是大神。Windows系统还是比黑苹果简单方便。
